# Generated by Django 5.1.4 on 2024-12-23 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('limite_inferior', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('limite_superior', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('periodicidade', models.PositiveIntegerField(help_text='Periodicidade em minutos')),
            ],
        ),
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_hora', models.DateField(auto_now_add=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotacoes', to='ativos.ativo')),
            ],
        ),
    ]
