# Generated by Django 5.1.4 on 2025-01-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0002_ativo_ultima_cotacao_alter_ativo_limite_inferior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='data_hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
